# Generated by Django 6.1.1 on 2026-09-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_medicalrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
