# Generated by Django 6.1.1 on 2026-09-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='vital_signs',
            field=models.TextField(blank=True),
        ),
    ]
