# Generated by Django 6.1.1 on 2026-09-11 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_labtestcategory_labtestrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSampleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=100)),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('collection_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_sample_collections', to=settings.AUTH_USER_MODEL)),
                ('lab_test_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample_collection', to='patients.labtestrequest')),
            ],
        ),
    ]
