# Generated by Django 6.1.1 on 2026-09-11 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_labtestprocessing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.TextField()),
                ('reference_range', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('result_notes', models.TextField(blank=True)),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='patients.labtestrequest')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
