# Generated by Django 6.1.1 on 2026-09-11 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_labtestresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Verified', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='patients.labtestresult')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
